---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluecosm-os
# description will be included in the image's metadata
description: This is my personal OS image with the Cosmic Desktop.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      cleanup: false # necessary for RPM stage not to fail
      nonfree: rpmfusion # enable RPM Fusion repositories (required for Steam, etc.)
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      copr:
        - ryanabx/cosmic-epoch # Cosmic Desktop packages
        - atim/starship
        - che/zed
        - kylegospo/system76-scheduler
    install:
      packages:
        - cosmic-desktop

        # Everything gaming
        - gamescope
        - mangohud
        - system76-scheduler
        - libva.i686 # To ensure that Steam is able to run in the RPM but there is still a chance that the 64 and 32 bit versions are not version matched

        # Devtools
        - ptyxis
        - tailscale

        # CLI tools
        - micro
        - starship

        # Intel graphics support
        - intel-gpu-tools
        - libva-utils

        # multimedia
        - vlc
        - mpv
        - ffmpeg
        - libavcodec-freeworld

        # Virtualization support for Windows guests
        - edk2-ovmf
        - swtpm

        # LLM requirements
        - intel-level-zero
        - intel-compute-runtime

        # Zed editor (RPM to avoid flatpak limitations)
        - zed
    group-install:
      packages:
        - virtualization
  - type: rpm-ostree
    install:
      - steam # specialized akmods module to avoid 32bit codec issues
      - steam-devices
  - type: akmods
    install:
      - kvmfr

  - type: brew
    nofile-limits: true

  - type: systemd
    system:
      enabled:
        - libvirtd.socket
        - virtnetworkd.socket
        - com.system76.Scheduler.service
        - tailscaled.service

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.vivaldi.Vivaldi
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
